# Generated by Django 2.0.4 on 2018-05-11 23:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEmision', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('folio', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=12)),
                ('provedor', models.CharField(max_length=12)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('clasificacion', models.CharField(max_length=12)),
                ('precio', models.FloatField()),
                ('descuento', models.IntegerField(default=0)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=25)),
                ('rfc', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=12)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmacia.Usuario'),
        ),
    ]
