# Generated by Django 2.0.4 on 2018-05-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='monto',
        ),
    ]
