# Generated by Django 2.0.4 on 2018-05-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_remove_factura_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
