# Generated by Django 2.0.4 on 2018-05-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_producto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
