# Generated by Django 2.0.4 on 2018-05-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_producto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='clasificacion',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='producto',
            name='folio',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='provedor',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='producto',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=25),
        ),
    ]
